### ISSUE TITLE
WHAT?

### ISSUE THREAD

**Issue by rxwei** [yshen47/izipper2#1]
What's this for?

**Comment by yshen47** [comment]
直接用这个吧，懒得把之前的改过来了

**Comment by xinranmsn** [comment]
这里面有别人的代码。不要用这个。

**Comment by xinranmsn** [comment]
I suggest continuing with our original project. Code change is as easy as copy & paste.

**Comment by yshen47** [comment]
那我再看看啊

**Comment by yshen47** [comment]
整乱了
